# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: rails
  password: rails
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Sample_development

test:
  <<: *default
  database: Sample_test

production:
  <<: *default
  database: Sample_production
  username: rails
  password: <%= ENV['rails'] %>
